# Generated by Django 5.2.3 on 2025-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('diameter', models.PositiveIntegerField(verbose_name='Диаметр')),
                ('season', models.CharField(choices=[('summer', 'Летняя'), ('winter', 'Зимняя'), ('allseason', 'Всесезонная')], max_length=10, verbose_name='Сезон')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
    ]
